apiVersion: v1
kind: Service
metadata:
  name: nginx-git-sync
  labels:
    app: nginx-git-sync
spec:
  type: ClusterIP
  selector:
    app: nginx-git-sync
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
